spring:
  profiles:
    active: dev

app:
  kafka:
    topic:
      chat-message: chat-message
  websocket:
    allowed-origins: http://localhost:8080

server:
  port: 8080
  shutdown: graceful

spring.lifecycle:
  timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
