spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:chat-group}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}

app:
  websocket:
    allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS}
